//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportRecords
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class user30_dbEntities : DbContext
    {
        public user30_dbEntities()
            : base("name=user30_dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<ddAchievement> ddAchievement { get; set; }
        public virtual DbSet<ddAchievementName> ddAchievementName { get; set; }
        public virtual DbSet<ddAchievementType> ddAchievementType { get; set; }
        public virtual DbSet<ddRole> ddRole { get; set; }
        public virtual DbSet<ddSport> ddSport { get; set; }
        public virtual DbSet<ddTeam> ddTeam { get; set; }
        public virtual DbSet<ddTournament> ddTournament { get; set; }
        public virtual DbSet<ddUser> ddUser { get; set; }
    }
}
