//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportRecords
{
    using System;
    using System.Collections.Generic;
    
    public partial class ddAchievement
    {
        public int id { get; set; }
        public Nullable<System.DateTime> date { get; set; }
        public string @event { get; set; }
        public Nullable<int> id_athlete { get; set; }
        public Nullable<int> id_tournament { get; set; }
        public Nullable<int> id_achievementName { get; set; }
        public Nullable<int> id_achievementType { get; set; }
        public Nullable<int> id_sport { get; set; }
    
        public virtual ddAchievementName ddAchievementName { get; set; }
        public virtual ddAchievementType ddAchievementType { get; set; }
        public virtual ddSport ddSport { get; set; }
        public virtual ddTournament ddTournament { get; set; }
        public virtual ddUser ddUser { get; set; }
    }
}
