//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SportRecords
{
    using System;
    using System.Collections.Generic;
    
    public partial class ddUser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ddUser()
        {
            this.ddAchievement = new HashSet<ddAchievement>();
        }
    
        public int id { get; set; }
        public string firstname { get; set; }
        public string lastname { get; set; }
        public string patronymic { get; set; }
        public Nullable<System.DateTime> birth_date { get; set; }
        public Nullable<int> id_team { get; set; }
        public Nullable<int> id_role { get; set; }
        public string login { get; set; }
        public string password { get; set; }
        public string gender { get; set; }
        public string photoPath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ddAchievement> ddAchievement { get; set; }
        public virtual ddRole ddRole { get; set; }
        public virtual ddTeam ddTeam { get; set; }
    }
}
